<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MyPc" failures="0" tests="10" name="assignment1.task1Test" time="219.934" errors="0" timestamp="2022-11-14T20:01:07 CET" skipped="0">
  <testcase classname="assignment1.task1Test" name="catchExcetionOnJsonObjectCreateDescription" time="27.386"/>
  <system-out/>
  <testcase classname="assignment1.task1Test" name="catchExcetionOnJsonObjectCreateImageUrl" time="27.387"/>
  <system-out/>
  <testcase classname="assignment1.task1Test" name="deleteAllAlerts" time="27.384"/>
  <system-out/>
  <testcase classname="assignment1.task1Test" name="createRightAmouontOfJsonObjException" time="0.422"/>
  <system-out/>
  <testcase classname="assignment1.task1Test" name="createRightAmouontOfJsonObj" time="27.385"/>
  <system-out/>
  <testcase classname="assignment1.task1Test" name="catchExcetionOnJsonObjectCreatePrice" time="27.387"/>
  <system-out/>
  <testcase classname="assignment1.task1Test" name="validURL" time="0.421"/>
  <system-out/>
  <testcase classname="assignment1.task1Test" name="catchExcetionOnJsonObjectCreateTitle" time="27.388"/>
  <system-out/>
  <testcase classname="assignment1.task1Test" name="catchExcetionOnJsonObjectCreateURL" time="27.388"/>
  <system-out/>
  <testcase classname="assignment1.task1Test" name="catchExcetionOnJsonObjectCreateAlertType" time="27.386"/>
  <system-out/>
</testsuite> <!-- assignment1.task1Test -->
